### ISSUE TITLE
caddy-gen can't see any containers

### ISSUE THREAD

**Issue by wdullaer** [alexex/caddy-gen#4]
Hey,

I've followed your tutorial to the letter, but can't get the caddy-gen container to put the details from the app to proxy into the Caddyfile.
The env vars are properly set (`LETSENCRYPTEMAIL` and `VIRTUAL_HOST`), but any container specific information is not filled.

I've googled around and found 2 issues in docker-gen and nginx-proxy which sound very similar to what I'm experiencing.
https://github.com/jwilder/docker-gen/issues/196
https://github.com/jwilder/nginx-proxy/issues/479
However I tried the solutions (remove `-only-exposed` from the `docker-gen` command and put all containers in external network), but they're not working for me.

I am using docker-compose (with a v3 file) to orchestrate the entire thing.
Any feedback or things I can test would be much appreciated.

Here's my docker-compose file for reference (without the tweaks suggested in the two linked issues)
```yaml
version: "3"
services:
  web:
    image: <my-image>
    restart: on-failure:5
    environment:
      - LOGGING_LEVEL=info
      - VIRTUAL_HOST=<my-hostname>
      - SERVER_PORT=80

  caddy-gen:
    image: alexanderjulo/caddy-gen:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - config:/etc/caddy
    links:
      - web
    environment:
      - LETSENCRYPT_EMAIL=<my-email>

  caddy:
    image: alexanderjulo/caddy
    command: caddy -restart=inproc -agree
    ports:
      - 80
      - 443
    links:
      - web
    volumes:
      - config:/srv
      - /root/ssl:/root/.caddy/letsencrypt

volumes:
  config:
    driver: local
```
Here's the Caddyfile that gets generated with this setup
```
<my-hostname> {
    tls <my-email>
    proxy / :80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
```
